Daily weather screen
AndresTorrico09/WeatherApp pull request #6
Opened 2021-05-31 17:58 UTC by AndresTorrico09

Forecast for next days screen (using mock images)

![image](https://user-images.githubusercontent.com/20949854/120227939-84577c00-c220-11eb-8ab2-0d41f3546ab8.png)

2021-07-05 15:56 UTC, huanachin commented on app/src/main/java/com/distillery/interview/ui/daily_weather/DailyWeatherAdapter.kt
> +    fun setItems(items: ArrayList<Daily>) {
Could we use DiffUtill?

2021-07-05 15:58 UTC, huanachin commented on app/src/main/java/com/distillery/interview/ui/daily_weather/DailyWeatherFragment.kt
> +        binding.rvDailyWeather.layoutManager = LinearLayoutManager(
Can we put this attribute in the XML?

2021-07-16 19:58 UTC, lucaslabs requested changes

2021-07-16 19:58 UTC, lucaslabs commented on app/src/main/java/com/distillery/interview/data/source/remote/WeatherRemoteDataSource.kt
> +        withContext(Dispatchers.IO) {
Noice!

2021-07-16 19:58 UTC, lucaslabs commented on app/src/test/java/com/distillery/interview/ui/DailyWeatherViewModelTests.kt
> +        Assert.assertEquals(
What about loading state?

2021-07-16 19:58 UTC, lucaslabs commented on app/src/test/java/com/distillery/interview/ui/DailyWeatherViewModelTests.kt
> +        Assert.assertEquals(
What about loading state?

2021-07-16 20:01 UTC, huanachin approved these changes

2021-07-16 20:01 UTC, huanachin commented on app/src/main/java/com/distillery/interview/ui/daily_weather/DailyWeatherFragment.kt
> +class DailyWeatherFragment : Fragment() {
Could we create a base fragment, and add some methods in common?

2021-07-16 20:08 UTC, lucaslabs approved these changes

2021-07-16 20:10 UTC, merged